### PR TITLE
Project setup

### PR DESCRIPTION
**Pull request by chumaachike**
Created a git branch "project-setup" where index.html and style.css have been created and edited. Both files have passed the linters test and they are ready to be merged

### CODE REVIEW

**Review by sja-thedude — CHANGES_REQUESTED** [review]
## Required Changes ♻️

Hi @chumaachike , This is @sja-thedude your code reviewer.

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Required - 
- [ ] Kindly add the Pull Request description according to the Project requirements.
- [ ] Make sure to fix stylelint linter by adding some code to the CSS file.

## Highlights
- Readme Professional 👍 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me [@sja-thedude] in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Review by smunozmo — CHANGES_REQUESTED** [review]
Hi @chumaachike , 👋  

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Highlights 👏 

- Great work using the right GitHub Flow.
- Your README looks professional, well done.
- Commits are descriptive, good work.

 ## Required Changes ♻️

- [ ]  You are almost there, please edit the Pull Request description as the previous reviewer said, this will make your repository look more professional, here's an [example](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/documentation/articles/professional_repo_rules.md) of a simple PR description.

_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._




Cheers and Happy coding! 🤓 

✅ Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

⚠️ **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Review by sinansevgi — COMMENTED** [review]
Hello @chumaachike  👋,

_This is an additional review as a result of the second opinion request._

- Documenting your code is one of the essential skills you should have as a developer. 
Being able to write good PR descriptions will be a great help in demonstrating your teamwork skills to employers. 

In the pull request description, you should explain what you’ve done, why you’ve done it, and how to prove it is ready to be merged into the main branch. 

- [ ] Please update your pull request description as requested and request another code review.

Keep rocking 🚀!
Sinan Sevgi

**Review by sinansevgi — COMMENTED** [review]
Hello @chumaachike  👋,

_This is an additional review as a result of the second opinion request._

I can see that you have now a well-written PR description. 

As this was the only reason that your project was not approved it will be approved as soon as possible.
Please note that since we will approve it manually so this could take a few hours!

Keep rocking 🚀!

**Pull request merged**
